name: Symskill test in custom docker image

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [felix_new_tasks, yifei_force_sensing]

jobs:
  test:
    runs-on: self-hosted
    container:
      image: ghcr.io/shaoyifei96/my-image:latest
      # docker has all the dependencies and datasets
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install robosuite # this is part of the docker, but since code is updated, need to install it again
        run: | # already installed with pip install -e robosuite
          cd /root/robosuite && \
          git pull 

      - name: install robocasa # this is part of the docker, but since code is updated, need to install it again
        run: | # already installed with pip install -e robocasa
          cd /root/robocasa && \
          git pull 

      - name: install ds_policy # this is part of the docker, but since code is updated, need to install it again
        run: | # already installed with pip install -e robocasa
          cd /root/ds_policy && \
          git pull 

      - name: Install Symskill
        run: |
          python3 -m pip install -e .
      - name: download datasets
        run: |
          git clone https://github.com/shaoyifei96/predicators_robocasa_files.git && \
          cp predicators_robocasa_files/* . && \
          mkdir -p /github/home/mosek && \
          cp predicators_robocasa_files/mosek.lic /github/home/mosek/mosek.lic 

      - name: Set PYTHONHASHSEED
        run: echo "PYTHONHASHSEED=0" >> $GITHUB_ENV

      - name: install osmesa
        run: |
          apt-get update && \
          apt-get install -y libosmesa6-dev freeglut3-dev libglfw3-dev libgles2-mesa-dev libosmesa6 && \
          echo "MUJOCO_GL=osmesa" >> $GITHUB_ENV

      - name: Run pytest
        run: |
          pytest --tb=short -rA --show-capture=stderr tests/test_sym_skill.py
      
      - name: upload feature data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: feature_data
          path: feature_data

      - name: upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results

      - name: upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: videos